#!/bin/bash

# Author: Samuel Brady

# This annotates FreeBayes variant calls using SnpEff, to indicate the effect
# of each variant (genes affected, whether mutations are missense, nonsense, etc.). It
# uses as input VCF data from the previous step (step a).
# Note that VCFs from the previous step (one VCF per chromosome is
# generated by the previous step) must be combined using an appropriate tool,
# such as VCFtools, into a single VCF that can be used as input to this step.

# This requires Java and SnpEff (we used v4-1g).

inputFile=	# input VCF file of FreeBayes output (all chromosome variants combined into one VCF)
outputFile=	# output VCF file with annotations added

java -Xmx4g -jar snpEff.jar -v hg19 $inputFile > $outputFile


